# Site settings
url: "http://hacquebordbuckles.nl"

# Assets
assets:
    debug: false
    js_compressor:  uglifier
    css_compressor: sass
    sources:
        - _assets/fonts
        - _assets/images
        - _assets/javascripts
        - _assets/stylesheets
